version: "3.8"
services:
  springboot:
    image: ghcr.io/graalvm/jdk-community:25
    container_name: aurora-springboot
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://aurora-mysql:3306/aurora?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATA_REDIS_HOST: aurora-redis
      SPRING_RABBITMQ_HOST: aurora-rabbitmq
      ELASTICSEARCH_REST_URIS: http://aurora-elasticsearch:9200
      UPLOAD_MINIO_ENDPOINT: http://aurora-minio:9000/
    ports:
      - "8080:8080"
    volumes:
      - /opt/aurora/app/aurora-springboot-0.0.1.jar:/app/blog.jar
    networks:
      - aurora-network
    restart: always
    command: >
      java -Xms64m -Xmx128m
           -XX:+UseSerialGC
           -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m
           -XX:ReservedCodeCacheSize=32m -Xss256k
           -XX:+UseCompressedOops -XX:+UseCompressedClassPointers
           -XX:+UseStringDeduplication -XX:+OptimizeStringConcat
           -Djava.security.egd=file:/dev/./urandom
           -Dspring.jmx.enabled=false
           -jar /app/blog.jar"

networks:
  aurora-network:
    external: true
